- .eslintrc.js
- .gitignore
- index.html
- package.json
- static/css/base.css
- static/js/newsletter_signup.js
- static/stylus/base.styl
- static/stylus/fonts.styl
We need to allow people to signup (using basket) for updates about View Source 2016, which happens in 2 locations. 
The HTML of the signup form was already implemented by @craigcook (I think); I just uncommented it and added a few elements pertaining to validation. 
The main target of this review should be the javascript to validate the form, do an asynchronous post, and handle error responses. 
Will ping @jpetto and @agibson for review.
> Add newsletter signup form

- source/js/newsletter.js
- source/stylesheets/components/newsletter.styl
Because Edge doesn't support :empty.
> Use JS to hide newsletter errors.

- tag-release.sh
@hoosteeno @stephaniehobson this is the [same script](https://github.com/mozilla/bedrock/blob/master/bin/tag-release.sh) we use for tagging releases on [bedrock](http://bedrock.readthedocs.io/en/latest/pipeline.html#push-to-master-tagged)
> Add tag-release.sh

- layouts/common.html
- layouts/landing.html
> Load javascript asynchronously.

- layouts/conference.html
As discussed with Justin. Fixes #80
> Link to #newsletter from speakers widget.

- Dockerfile
- nginx.conf
Allow for easy nginx previews with 'make serve'
Switch deploy image to deis-base 0.3.0 based on ubuntu-slim
> Make http->https redirect conditional on env var

- nginx.conf
HSTS, X-frame, X-XSS, and content type improvements following recommendations on https://securityheaders.io/?q=https%3A%2F%2Fviewsourceconf.org%2F
> Improve security headers

- data/conferences.json
- source/berlin-2016/cfp.html
> Close the CFP for Berlin. July 4th.

- layouts/conference.html
- layouts/includes/session.html
- source/js/01_utils.js
- source/js/02_analytics.js
- source/js/expand.js
- source/js/newsletter.js
- source/js/speakers.js
- source/styles.html
- source/stylesheets/components/button.styl
- source/stylesheets/components/hotels.styl
- source/stylesheets/components/session.styl
- source/stylesheets/components/split.styl
- source/stylesheets/style.styl
- source/stylesheets/utilities/hidden.styl
- source/stylesheets/utilities/utilities.styl
- add expands functionality
- add expands functionality to hotel suggestions
- change session summaries to use expands functionality
- rename and improve parentByClass
- start tracking buttons
- stop tracking speaker expands twice
- alphabetize style includes
- remove errant console log
- remove old hide/show functionality
> Add expands functionality

- source/styles.html
- source/stylesheets/includes/variables.styl
Remove Seattle theme.
Kept custom styles for hero so newsletter signup page looks pretty spiffy still.
> Remove Seattle theme

- layouts/includes/sessionteaser.html
- source/stylesheets/components/sessionteaser.styl
- fix that Apple strips anchors from some types of url >_<
- make link take up full title.
- optimizations for small screen.
> Session teaser fix.

- layouts/landing.html
- source/stylesheets/components/split.styl
> Convert 'split' to single conference

- layouts/includes/groupdetails.html
- layouts/includes/session.html
- layouts/includes/sessiondetails.html
- layouts/schedule.html
- source/stylesheets/components/session.styl
- move moderator names under session names
- split group sessions out from talk sessions in template logic
- remove special treatment of session_title below 480px
- display tweaks
> Schedule Tweaks

- layouts/conference.html
- source/data/berlin_sponsors.yaml
Added name to model and referenced it in sponsor macro.
Fix. #145
> Add alt text to sponsor logos

- nginx-ssl.conf
- nginx.conf
Add CSP.
And serve WOFF2 files as fonts.
Special attention paid to:
- SVG images
- newsletter submission
- Google Maps and Google Analytics
- videos in /2015/
> Add Content Security Policy

- layouts/common.html
- layouts/landing.html
- source/js/00_global.js
- source/js/01_utils.js
- source/js/02_analytics.js
- source/js/hero.js
- source/js/newsletter.js
- source/js/speakers.js
Feature testing for devicePixelRatio which should target IE11 and up as recommended here: https://sixtwothree.org/posts/cutting-the-mustard-revisited
Needs testing in IE, iOS, and Android.
> Switch to feature test instead of conditional comments

- layouts/schedule.html
- source/js/01_utils.js
- source/js/expand.js
- source/stylesheets/components/session.styl
- source/stylesheets/utilities/size.styl
- source/stylesheets/utilities/utilities.styl
- added utility to get screen size from media queries in javascript
- works if you resize the screen
- works without javascript (defaults open)
- opens day by default if it is current day of conference
- opens day by default if it is linked to
> Add expand/collapse on mobile for sessions

- source/data/conferences.yaml
> Day 2 Edits

- layouts/conference.html
- source/data/conferences.yaml
- Removed sponsorship information
- Moved newsletter higher & changed copy
- Removed "in progress" announcement
> Day 3 Edits

- Jenkinsfile
- Jenkinsfiles/default.groovy
- Jenkinsfiles/default.yml
- Jenkinsfiles/master.yml
- Jenkinsfiles/prod.yml
- Makefile
- README.md
example [staging push](https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_k8s/job/dp_k8s_pipeline/16/)
example [prod push](https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_k8s/job/prod/2/)
> add Deis Workflow deployment automation

- Jenkinsfiles/default.groovy
- Jenkinsfiles/default.yml
- Jenkinsfiles/master.yml
- Jenkinsfiles/prod.yml
https://ci.us-west.moz.works/blue/organizations/jenkins/viewsourceconf_deploy_k8s/detail/dp_multi_k8s/1/pipeline
> multi region k8s deployment

- layouts/landing.html
- source/stylesheets/base/elements/document.styl
This page gets seen until the redirect is fixed, so I'm making it more presentable.
Also stripping JS and analytics in an attempt to make it load and redirect faster.
> Better landing page

- README.md
- bin/irc-notify.sh
- deploy_to_prod.sh
https://github.com/mozmeao/infra/issues/1043
> update jenkins to use vpn
